
services:
  mongo-products:
    image: mongo:6.0
    container_name: bakery-products-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: product_user
      MONGO_INITDB_ROOT_PASSWORD: product_password
      MONGO_INITDB_DATABASE: bakery_products
    volumes:
      - mongo_products_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - bakery-network

volumes:
  mongo_products_data:
    driver: local

networks:
  bakery-network:
    driver: bridge
