# Docker-specific configuration
spring:
  data:
    mongodb:
      uri: mongodb://product_user:product_password@mongodb:27017/bakery_products?authSource=admin

# Eureka Configuration for Docker
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: product-service

# Server Configuration
server:
  port: 8083

# Logging for Docker
logging:
  level:
    com.blubugtech.bakery_product_service: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
