spring:
  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USER}
    password: ${PRODUCT_DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT_PRODUCT}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
r2:
  endpoint: ${R2_ENDPOINT}
  cdn-base-url: ${R2_CDN_URL}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
